sdt_payment:
    resource: "@SdtPaymentBundle/Resources/config/routing.yml"
    prefix:   /

sdt_session:
    resource: "@SdtSessionBundle/Resources/config/routing.yml"
    prefix:   /

sdt_core:
    resource: "@SdtCoreBundle/Resources/config/routing.yml"
    prefix:   /

SdtAdvertBundle:
    resource: "@SdtAdvertBundle/Resources/config/routing.yml"
    prefix:   /

SdtScoreBundle:
    resource: "@SdtScoreBundle/Resources/config/routing.yml"
    prefix:   /

SdtTutorialBundle:
    resource: "@SdtTutorialBundle/Resources/config/routing.yml"
    prefix:   /

SdtMessageBundle:
    resource: "@SdtMessageBundle/Resources/config/routing.yml"
    prefix:   /

SdtNewsBundle:
    resource: "@SdtNewsBundle/Resources/config/routing.yml"
    prefix:   /

SdtForumBundle:
    resource: "@SdtForumBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_impersonating:
    pattern: /admin/dashboard
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

ornicar_message:
    resource: "@OrnicarMessageBundle/Resources/config/routing.xml"
    prefix: /mp

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@ApplicationSonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_media_pixlr:
    resource: '@SonataMediaBundle/Resources/config/routing/pixlr.xml'
    prefix: /admin/media

user_profile:
    resource: '@ApplicationSonataUserBundle/Resources/config/routing/profile.xml'
    prefix: /

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google